<?php

namespace AppBundle\Repository;

/**
 * IngredientFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientFamilyRepository extends \Doctrine\ORM\EntityRepository
{
}
