<?php

namespace AppBundle\Repository;

/**
 * IngredientsCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientsCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
