<?php declare(strict_types=1);
/**
 * PHP version 7
 *
 * Created by PhpStorm.
 * User: alexandre_vinet
 * Date: 09/11/17
 * Time: 09:06
 *
 * @category   Symfony-Exam
 *
 * @package    AppBundle
 *
 * @subpackage AppBundle\Repository
 *
 * @author     Alexandre Vinet <contact@alexandrevinet.fr>
 */

namespace AppBundle\Repository;

use AppBundle\Entity\Ingredient;
use Doctrine\ORM\EntityRepository;

/**
 * IngredientRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends EntityRepository
{
    /**
     * @param string $name
     * @param string $category
     *
     * @return Ingredient[]
     */
    public function findByNameOrCategory(?string $name, ?string $category): array
    {
        $qb = $this->createQueryBuilder('ingredient');

        if ($name) {
            $qb
                ->andWhere('ingredient.origfdnm LIKE :name')
                ->setParameter('name', '%'.$name.'%')
            ;
        }

        if ($category) {
            $qb
                ->leftJoin('ingredient.category', 'category')
                ->andWhere('category.origgpfr LIKE :category')
                ->setParameter('category', '%'.$category.'%')
            ;
        }

        return $qb->getQuery()->getResult();
    }
}
